import { useState } from 'react'
import type { FormEvent } from 'react'
import { useParams } from 'react-router-dom'
import { AppLayout } from '../../layouts/AppLayout'
import { formatCompactNumber } from '../../lib/format'
import { trendingPolls } from '../../services/homeService'

const initialComments = ['AI has so much potential for education and healthcare.', 'We need thoughtful rules before it moves too quickly.', 'The future is here — we just need to adapt.']

export function PollPage() { const {id='1'}=useParams(); const poll=trendingPolls.find(item=>item.id===id) ?? trendingPolls[0]; const [vote,setVote]=useState<'yes'|'no'|null>(null); const [liked,setLiked]=useState(false); const [saved,setSaved]=useState(false); const [comment,setComment]=useState(''); const [comments,setComments]=useState(initialComments); const yes=poll.yesPercent+(vote==='yes'?1:0); const submitComment=(event:FormEvent)=>{event.preventDefault();const value=comment.trim();if(value){setComments(old=>[value,...old]);setComment('')}}; return <AppLayout><section className="poll-detail"><img src={poll.image} alt=""/><div><span className="category-badge">{poll.category}</span><h1>{poll.title}</h1><p>Join the global conversation and see what people around the world think.</p><div className="vote-buttons"><button className={vote==='yes'?'voted yes':''} onClick={()=>setVote('yes')}>Yes <b>{yes}%</b></button><button className={vote==='no'?'voted no':''} onClick={()=>setVote('no')}>No <b>{100-yes}%</b></button></div><div className="progress large"><i style={{width:`${yes}%`}}/></div><small>{formatCompactNumber(poll.votes + (vote?1:0))} total votes</small><div className="poll-actions"><button onClick={()=>setLiked(!liked)}>{liked?'♥ Liked':'♡ Like'}</button><button onClick={()=>navigator.clipboard?.writeText(location.href)}>↗ Share</button><button onClick={()=>setSaved(!saved)}>{saved?'▰ Saved':'▱ Save'}</button></div></div></section><section className="comments"><h2>Comments <small>({2341 + comments.length - initialComments.length})</small></h2><form onSubmit={submitComment}><input value={comment} onChange={event=>setComment(event.target.value)} placeholder="Add to the conversation..."/><button>Post</button></form>{comments.map((text,index)=><article key={`${text}-${index}`}><i className="avatar">{index===0&&comments.length>initialComments.length?'GV':['AM','WV','TL'][index] ?? 'GV'}</i><div><b>{index===0&&comments.length>initialComments.length?'GlobalVoter':['Alex_M','WorldVoice','TechLover'][index] ?? 'GlobalVoter'}</b><small>{index===0&&comments.length>initialComments.length?'Just now':`${index+2}h ago`}</small><p>{text}</p><button>♡ {128-index*22}</button></div></article>)}</section></AppLayout> }
