import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Footer } from '../components/Footer'
import { Navbar } from '../components/Navbar'
import { SectionHeading } from '../components/SectionHeading'
import { formatCompactNumber } from '../lib/format'
import { categories, exploreFeed, trendingPolls } from '../services/homeService'

function Hero() { const stats = [['250K+', 'Total Users'], ['2.4M', 'Total Votes'], ['8.5K', 'Active Polls'], ['195', 'Countries']]; return <section className="hero-section"><div className="hero-glow" /><div className="hero-grid"><div className="hero-copy"><span className="live-badge">⌁ Live platform · 195 countries voting</span><div><h1>See what the world<br />thinks. <strong>In real time.</strong></h1><p>Vote, discover opinions and see real-time results from people around the globe. Join millions already shaping global conversation.</p></div><div className="hero-cta"><Link className="primary-button" to="/explore">Explore Polls <b>→</b></Link><Link className="secondary-button" to="/map">◎ View World Map</Link></div><div className="join"><div className="avatar-stack">{['A', 'B', 'C', 'D'].map(letter => <span key={letter}>{letter}</span>)}</div>Join <b>250,000+</b> users worldwide</div><div className="hero-stats">{stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></div><div className="map-card"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/a34455bc-0852-4c1c-8d69-559cd1ba0d05-oGiwmg1s8PYU0PIvOxCwgf2NYsVSJu.png" alt="World map showing global opinion data" /><div className="map-shade" />{[['72%', 'Agree', 'a'], ['58%', 'Neutral', 'b'], ['64%', 'Agree', 'c'], ['81%', 'Agree', 'd'], ['47%', 'Disagree', 'e']].map(([value, label, pos]) => <div className={`map-bubble ${pos} ${label.toLowerCase()}`} key={pos}><b>{value}</b><small>{label}</small></div>)}<div className="map-live"><i /> Live Map <em /> Real-time results <em /> Global opinions</div></div></div></section> }

function Trending() { return <section className="section"><div className="split"><div><SectionHeading icon="♨" title="Trending Now" subtitle="The most voted topics right now" action={<Link className="view-all" to="/explore">View all →</Link>} /><div className="poll-grid">{trendingPolls.map(poll => <Link className="poll-card" to={`/poll/${poll.id}`} key={poll.id}><div className="poll-image"><img src={poll.image} alt={poll.title} />{poll.trending && <span className="trend-tag">♨ Trending</span>}{poll.live && <span className="live-tag">⌁ Live</span>}</div><div className="poll-body"><div><span className="category-badge">{poll.category}</span><h3>{poll.title}</h3></div><div className="result"><div><span>{poll.yesPercent}%</span><span>{poll.noPercent}%</span></div><div><i style={{ width: `${poll.yesPercent}%` }} /></div></div><small>♙ {formatCompactNumber(poll.votes)} votes <time>{poll.timeAgo}</time></small></div></Link>)}</div></div><StatsSidebar /></div></section> }
function StatsSidebar() { const stats = [['🗳', 'Votes Today', '1.2M', '+18.6%'], ['👥', 'Active Users', '85.4K', '+12.4%'], ['▥', 'Polls Created', '312', '+7.8%'], ['🌍', 'Countries Voting', '195', '+9.3%']]; return <aside className="sidebar"><div className="panel"><h3>〽 Live Stats</h3>{stats.map(([icon, label, value, change]) => <div className="stat-row" key={label}><span>{icon} {label}</span><b>{value}</b><i>{change}</i></div>)}<Link to="/statistics" className="outline-button">View Full Statistics</Link></div><div className="panel countries"><h3>Top Countries Today</h3>{[['🇸🇬', 'Singapore', '89%'], ['🇸🇪', 'Sweden', '87%'], ['🇯🇵', 'Japan', '85%'], ['🇨🇦', 'Canada', '82%'], ['🇩🇪', 'Germany', '81%']].map(([flag, country, percent], index) => <div key={country}><small>{index + 1}.</small><span>{flag}</span><b>{country}</b><i>{percent}</i></div>)}</div></aside> }
function Categories() { return <section className="section top-border"><SectionHeading title="Explore Categories" subtitle="Browse all topics and find polls that interest you" /><div className="category-grid">{categories.map(category => <Link to="/categories" className="category-card" key={category.id}><span>{category.icon}</span><b>{category.name}</b><small>{formatCompactNumber(category.polls)} polls</small></Link>)}</div></section> }
function Feed() { const [liked, setLiked] = useState<Record<string, boolean>>({}); return <section className="section top-border"><div className="feed-layout"><div><h2 className="feed-title">Explore Feed</h2><div className="feed-list">{exploreFeed.map(item => <article className="feed-card" key={item.id}><div className="feed-user"><div className="avatar">{item.user.initials}</div><div><b>{item.user.name} <span>{item.user.country}</span></b><small>{item.user.username} · {item.timeAgo}</small></div><button aria-label="More options">•••</button></div><Link to={`/poll/${item.id}`}><span className="category-badge">{item.category}</span><h3>{item.poll}</h3></Link><Link to={`/poll/${item.id}`} className="feed-result"><div><b>Yes — {item.result.yes}%</b><b>No — {item.result.no}%</b></div><span><i style={{ width: `${item.result.yes}%` }} /></span><small>{formatCompactNumber(item.result.votes)} total votes</small></Link><div className="feed-actions"><button onClick={() => setLiked(old => ({ ...old, [item.id]: !old[item.id] }))} className={liked[item.id] ? 'liked' : ''}>♡ Like</button><button>▢ {formatCompactNumber(item.comments)}</button><button>↗ Share</button><button>▱ Save</button></div></article>)}</div></div><FeedSidebar /></div></section> }
function FeedSidebar() { const people = [['GV', 'GlobalVoter', 342], ['PN', 'PoliticsNerd', 198], ['TO', 'TechOracle', 156], ['WW', 'WorldWatcher', 143]]; return <aside className="sidebar feed-sidebar"><div className="panel"><h3>Top Creators This Week</h3>{people.map(([initials, name, count]) => <div className="creator" key={String(name)}><span className="avatar">{initials}</span><div><b>{name}</b><small>{count} polls created</small></div><button>Follow</button></div>)}</div><div className="panel topics"><h3>Trending Topics</h3>{['#AIDebate', '#WorldLeaders2030', '#ClimateAction', '#MarsColony', '#ElectricVehicles'].map((topic, index) => <Link to="/trending" key={topic}><b>{topic}</b><small>{[125, 98, 72, 61, 54][index]}K votes today</small><i>+{[18, 14, 11, 8, 6][index]}%</i></Link>)}</div></aside> }
export function HomePage() { return <><Navbar /><main><Hero /><Trending /><Categories /><Feed /></main><Footer /></> }
